name: Deploy pygbag to GitHub Pages

# Trigger the action on push to the master branch
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # Use the Python version required by pygbag

    # Step 3: Install pygbag
    - name: Install pygbag
      run: |
        python -m pip install --upgrade pip
        pip install pygbag

    # Step 4: Build the project with pygbag
    - name: Build with pygbag
      run: |
        pygbag --build --ume_block=0 --template hex.tmpl .

    # Step 5: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/web
